[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.85"
ct-api = { git = "https://github.com/code-tanks/code-tanks" }

[lib]
name = "my_tank"
path = "src/my_tank.rs"